application: tbly-nhs
version: 2
runtime: python
api_version: 1

handlers:
- url: /static/.*
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

- url: /test/.*
  script: admin.py
  login: admin

- url: /.*
  script: api.py

builtins:
- remote_api: on
- datastore_admin: on
